### PR TITLE
Draft: Feat/clippy 55

### PR DESCRIPTION
**Pull request by IvanJuricic**
Add PDF preview using PDF.js

### CODE REVIEW

**Comment by MihaelsGit** [comment]
Nice job @IvanJuricic  👏 we finally have clickable text 🎉 

I just want to check something before I approve the PR, did you try to open a link from the PDF and nagivate yourself back to our app via back button in browser toolbar? When I do that the PDF doesn't render itself. Can you check if that is also happening to you and see where the issue might be? It seems to me that the PDF doesn't render itself. The error that I see is this:
Screenshot 2022-12-18 at 14 51 43


Also clicking on a reference that navigates you to the references page makes the PDF zoomed 🤔

**Comment by AvendoOT** [comment]
> 

The state invalidates and because of that GET to middleware at /file doesn't get the ID of the file we want to preview.
The solution would be for preview to be at url with sufix /ID and then when it rerenders it would call the correct GET endpoint.
@IvanJuricic @MihaelsGit

**Comment by AvendoOT** [comment]
@IvanJuricic update .gitignore for build file and the rest of the generated folders so we dont have 12k changes

**Review by MihaelsGit — COMMENTED** [review]
I've tested the new changes and the zooming actually changes the page instead of zooming @IvanJuricic 


EDIT: 
Zooming and navigation work as expected 👏 
The only 2 things I'm having concerns about is opening link in the same tab - preserving state (I guess @AvendoOT needs to first implement the api call change on backend before we implement it on the frontend) and if those files in /build path are generated during build time? If yes, as Leon mentioned, we can add them to the .gitignore

**Review by patr1ck001 — APPROVED** [review]

**Comment by IvanJuricic** [comment]
Build folder is already in the .gitignore file

**Pull request merged**
